### ISSUE TITLE
Access denied for user 'oxid'@'localhost' when running runtests

### ISSUE THREAD

**Issue by alfredbez** [OXID-eSales/oxvm_eshop#17]
I can't run `runtest`, maybe I forgot to do something?
```
vagrant@oxideshop:/var/www/oxideshop/source/vendor/bin$ ./runtests
=========
running php version 5.5.9-1ubuntu4.14

============
Adding unit tests from /var/www/oxideshop/tests/Unit/Core/*Test\.php
PHP Fatal error:  Uncaught exception 'oxAdoDbException' with message 'mysqli error: [1045: Access denied for user 'oxid'@'localhost' (using password: YES)] in EXECUTE (SELECT * INTO OUTFILE '/tmp//oxid_dbdump/test//oxacceptedterms_dump.sql' FROM oxacceptedterms, Array) with user oxid
' in /var/www/oxideshop/source/Core/adodblite/adodb-exceptions.inc.php:84
Stack trace:
#0 /var/www/oxideshop/source/Core/adodblite/adodbSQL_drivers/mysqli/mysqli_driver.inc(359): adodb_throw('mysqli', 'EXECUTE', 1045, 'Access denied f...', 'SELECT * INTO O...', Array, Object(object_ADOConnection))
#1 /var/www/oxideshop/source/Core/adodblite/adodb.inc.php(316): mysqli_driver_ADOConnection->do_query('SELECT * INTO O...', -1, -1, Array)
#2 /var/www/oxideshop/source/Core/LegacyDatabase.php(180): ADOConnection->Execute('SELECT * INTO O...', Array)
#3 /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/Services/Library/DatabaseRestorer/DatabaseRestorerLocal.php(93): OxidEsales\Eshop\Core\LegacyDatabase->execute('SELECT * INTO O...')
#4  in /var/www/oxideshop/source/Core/adodblite/adodb-exceptions.inc.php on line 84

Fatal error: Uncaught exception 'oxAdoDbException' with message 'mysqli error: [1045: Access denied for user 'oxid'@'localhost' (using password: YES)] in EXECUTE (SELECT * INTO OUTFILE '/tmp//oxid_dbdump/test//oxacceptedterms_dump.sql' in /var/www/oxideshop/source/Core/adodblite/adodb-exceptions.inc.php on line 84

oxAdoDbException: mysqli error: [1045: Access denied for user 'oxid'@'localhost' (using password: YES)] in EXECUTE (SELECT * INTO OUTFILE '/tmp//oxid_dbdump/test//oxacceptedterms_dump.sql' FROM oxacceptedterms, Array) with user oxid
 in /var/www/oxideshop/source/Core/adodblite/adodb-exceptions.inc.php on line 84

Call Stack:
    0.0004     224680   1. {main}() /var/www/oxideshop/source/vendor/phpunit/phpunit/phpunit:0
    0.0154     468896   2. PHPUnit_TextUI_Command::main() /var/www/oxideshop/source/vendor/phpunit/phpunit/phpunit:47
    0.0154     469544   3. PHPUnit_TextUI_Command->run() /var/www/oxideshop/source/vendor/phpunit/phpunit/src/TextUI/Command.php:100
    1.0070    3575416   4. PHPUnit_Runner_BaseTestRunner->getTest() /var/www/oxideshop/source/vendor/phpunit/phpunit/src/TextUI/Command.php:123
    1.0176    3776320   5. ReflectionMethod->invoke() /var/www/oxideshop/source/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:86
    1.0176    3776488   6. AllTestsRunner::suite() /var/www/oxideshop/source/vendor/phpunit/phpunit/src/Runner/BaseTestRunner.php:86
    1.1376    3846048   7. AllTestsRunner::_addFilesToSuite() /var/www/oxideshop/source/vendor/oxid-esales/testing-library/AllTestsRunner.php:69
    1.1377    3859136   8. PHPUnit_Framework_TestSuite->addTestFile() /var/www/oxideshop/source/vendor/oxid-esales/testing-library/AllTestsRunner.php:155
    1.1405    4064984   9. PHPUnit_Framework_TestSuite->addTestSuite() /var/www/oxideshop/source/vendor/phpunit/phpunit/src/Framework/TestSuite.php:381
    1.1405    4065240  10. PHPUnit_Framework_TestSuite->__construct() /var/www/oxideshop/source/vendor/phpunit/phpunit/src/Framework/TestSuite.php:297
    1.1407    4193016  11. PHPUnit_Framework_TestSuite->addTestMethod() /var/www/oxideshop/source/vendor/phpunit/phpunit/src/Framework/TestSuite.php:195
    1.1408    4194136  12. PHPUnit_Framework_TestSuite::createTest() /var/www/oxideshop/source/vendor/phpunit/phpunit/src/Framework/TestSuite.php:880
    1.1445    4215912  13. OxidEsales\TestingLibrary\UnitTestCase->__construct() /var/www/oxideshop/source/vendor/phpunit/phpunit/src/Framework/TestSuite.php:582
    1.1446    4219232  14. OxidEsales\TestingLibrary\UnitTestCase->setUpBeforeTestSuite() /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/UnitTestCase.php:103
    1.1472    4225504  15. OxidEsales\TestingLibrary\UnitTestCase->backupDatabase() /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/UnitTestCase.php:121
    1.1626    4235496  16. OxidEsales\TestingLibrary\Services\Library\DatabaseRestorer\DatabaseRestorerLocal->dumpDB() /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/UnitTestCase.php:891
    1.1648    4249752  17. OxidEsales\Eshop\Core\LegacyDatabase->execute() /var/www/oxideshop/source/vendor/oxid-esales/testing-library/library/Services/Library/DatabaseRestorer/DatabaseRestorerLocal.php:93
    1.1648    4249888  18. ADOConnection->Execute() /var/www/oxideshop/source/Core/LegacyDatabase.php:180
    1.1648    4249984  19. mysqli_driver_ADOConnection->do_query() /var/www/oxideshop/source/Core/adodblite/adodb.inc.php:316
    1.1650    4250688  20. adodb_throw() /var/www/oxideshop/source/Core/adodblite/adodbSQL_drivers/mysqli/mysqli_driver.inc:359
```
However connection to database works via `mysql`:
```
vagrant@oxideshop:/var/www/oxideshop/source/vendor/bin$ mysql -u oxid -poxid oxid
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 101
Server version: 5.5.47-0ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

Where can I check which database credentials are used?

**Comment by Sieg** [comment]
Hi! Is your config.inc.php filled correctly?

**Comment by alfredbez** [comment]
```
vagrant@oxideshop:/var/www/oxideshop/source$ head config.inc.php -n 28 | tail -n 5
    $this->dbType = 'mysqli';
    $this->dbHost = 'localhost'; // database host name
    $this->dbName = 'oxid'; // database name
    $this->dbUser = 'oxid'; // database user name
    $this->dbPwd = 'oxid'; // database user password
```

**Comment by rezonanc-oxid** [comment]
Any `personal.yml` or `~/.personal_ansible_vm.yml` configuration overrides present?
What is your host environment? What hypervisor or VM provider are you using?

**Comment by alfredbez** [comment]
no `personal.yml` or `~/.personal_ansible_vm.yml`.

```
$ cat /etc/issue && uname -r                                                                                                                                         
Ubuntu 16.04 LTS \n \l

4.4.0-22-generic
```
I'm using VirtualBox.

**Comment by rezonanc-oxid** [comment]
I know that this might not be the best suggestion in the world, but just to double check, could you please do a fresh clone of https://github.com/OXID-eSales/oxvm_eshop repository where it's master branch is pointing to: https://github.com/OXID-eSales/oxvm_eshop/commit/cba519dfcc2bb80f0bc351d08e433ebe3bdae7b7
and base_vm points to: https://github.com/OXID-eSales/oxvm_base/commits/bec4f0ae94e54483ec7957043b838e36667adc94
oxideshop shared folder reflects: https://github.com/OXID-eSales/oxideshop_ce/commit/b4bc43498820d394793fd475285e118a79a74b92

I'll try to do the same and reproduce this issue.

**Comment by alfredbez** [comment]
Works now for me, I've no idea what was wrong...
