### ISSUE TITLE
vagrant-triggers plugin is not compatible with vagrant 2.2.7

### ISSUE THREAD

**Issue by patrick-blom** [OXID-eSales/oxvm_eshop#45]
Hi team,
I followed the instructions for the oxvm_setup and got the following error on the vagrant up command.

**Message:**
```
~/repositories/github/oxvm_eshop(b-6.1) » vagrant up                                                               
WARNING: Vagrant has detected the `vagrant-triggers` plugin. This plugin conflicts
with the internal triggers implementation. Please uninstall the `vagrant-triggers`
plugin and run the command again if you wish to use the core trigger feature. To
uninstall the plugin, run the command shown below:

  vagrant plugin uninstall vagrant-triggers

Note that the community plugin `vagrant-triggers` and the core trigger feature
in Vagrant do not have compatible syntax.

To disable this warning, set the environment variable `VAGRANT_USE_VAGRANT_TRIGGERS`.
/opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/logger.rb:43:in `validate_name': stack level too deep (SystemStackError)
	from /opt/vagrant/embedded/gems/2.2.7/gems/log4r-1.1.10/lib/log4r/logger.rb:30:in `initialize'
	from /home/patrick/.vagrant.d/gems/2.4.9/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:12:in `new'
	from /home/patrick/.vagrant.d/gems/2.4.9/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:12:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:122:in `new'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:122:in `finalize_action'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:36:in `block in initialize'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:36:in `map'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/action/warden.rb:36:in `initialize'
	 ... 10179 levels...
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:983:in `process_configured_plugins'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/lib/vagrant/environment.rb:178:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:145:in `new'
	from /opt/vagrant/embedded/gems/2.2.7/gems/vagrant-2.2.7/bin/vagrant:145:in `<main>'

```

**Vagrant version:**
```
~/repositories/github/oxvm_eshop(b-6.1) » vagrant --version                                                              
Vagrant 2.2.7
```

**Operating System:**
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

It seems that the vagrant-triggers plugin is not compatible with the latest vagrant version 2.2.7

How can I fix that problem and is the plugin still needed ?

Cheers Patrick

**Comment by flow-control** [comment]
Hey @patrick-blom,

thanks for posting this issue, not that it is a solution, but depending on your use case you might be able to use https://github.com/OXID-eSales/docker-eshop-sdk
Tell me if this worked.

Kind regards
Florian

**Comment by patrick-blom** [comment]
Hey @flow-control,
thx for the response! I'll give it try and report some Feedback.

Cheers Patrick

**Comment by patrick-blom** [comment]
Hey @flow-control,
I tried to set it up. Sadly it fails with the following message:

```

Successfully built b64a908b6a77
Successfully tagged docker-eshop-sdk_php:latest
WARNING: Image for service php was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Cannot create cache directory /home/oxid/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/oxid/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.3 but your PHP version (7.2.29) does not satisfy that requirement.
  Problem 2
    - Installation request for oxid-esales/oxideshop-doctrine-migration-wrapper dev-master -> satisfiable by oxid-esales/oxideshop-doctrine-migration-wrapper[dev-master].
    - oxid-esales/oxideshop-doctrine-migration-wrapper dev-master requires php ^7.3 -> your PHP version (7.2.29) does not satisfy that requirement.
  Problem 3
    - Installation request for oxid-esales/oxideshop-demodata-installer dev-master -> satisfiable by oxid-esales/oxideshop-demodata-installer[dev-master].
    - oxid-esales/oxideshop-demodata-installer dev-master requires php >=7.3 -> your PHP version (7.2.29) does not satisfy that requirement.
  Problem 4
    - Installation request for oxid-esales/oxideshop-composer-plugin dev-master -> satisfiable by oxid-esales/oxideshop-composer-plugin[dev-master].
    - oxid-esales/oxideshop-composer-plugin dev-master requires php ^7.3 -> your PHP version (7.2.29) does not satisfy that requirement.
  Problem 5
    - Installation request for oxid-esales/oxideshop-unified-namespace-generator dev-master -> satisfiable by oxid-esales/oxideshop-unified-namespace-generator[dev-master].
    - oxid-esales/oxideshop-unified-namespace-generator dev-master requires php ^7.3 -> your PHP version (7.2.29) does not satisfy that requirement.
  Problem 6
    - Installation request for oxid-esales/oxideshop-ide-helper dev-master -> satisfiable by oxid-esales/oxideshop-ide-helper[dev-master].
    - oxid-esales/oxideshop-ide-helper dev-master requires php >=7.3 -> your PHP version (7.2.29) does not satisfy that requirement.
  Problem 7
    - phpunit/php-code-coverage 8.0.x-dev requires php ^7.3 -> your PHP version (7.2.29) does not satisfy that requirement.
    - phpunit/php-code-coverage 8.0.1 requires php ^7.3 -> your PHP version (7.2.29) does not satisfy that requirement.
    - phpunit/php-code-coverage 8.0.0 requires php ^7.3 -> your PHP version (7.2.29) does not satisfy that requirement.
    - oxid-esales/testing-library dev-master requires phpunit/php-code-coverage ^8 -> satisfiable by phpunit/php-code-coverage[8.0.0, 8.0.1, 8.0.x-dev].
    - Installation request for oxid-esales/testing-library dev-master -> satisfiable by oxid-esales/testing-library[dev-master].

Makefile:33: recipe for target 'data/oxideshop/composer.lock' failed
make: *** [data/oxideshop/composer.lock] Error 2

```
Looks like, a container uses the wrong PHP Version.

Cheers Patrick

**Comment by flow-control** [comment]
Thanks for the feedback, can you try updating the PHP version in the `.env` file to 7.3?
We should then update the default in `.env.dist`

**Comment by patrick-blom** [comment]
Hi @flow-control,
I set the value. It ended up with this error:

```
Successfully built a33f46aea14a
Successfully tagged docker-eshop-sdk_php:latest
WARNING: Image for service php was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Cannot create cache directory /home/oxid/.composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/oxid/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 113 installs, 0 updates, 0 removals

                                                                      
  [RuntimeException]                                                  
  /var/www/oxideshop/vendor does not exist and could not be created.  
                                                                      

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

Makefile:33: recipe for target 'data/oxideshop/composer.lock' failed
make: *** [data/oxideshop/composer.lock] Error 1
```
My first thought was, that something went wrong during the build. So I cloned the repo again and removed the docker image, but the result was the same error oO 

Cheers Patrick

**Comment by patrick-blom** [comment]
Hey @flow-control 
thx again for your support. The containers are now up'n running.

Solution: 
- pull the latest master of the repository
- edit the `.env` file and change the HOST_USER_ID & HOST_GROUP_ID to the one of my user
- rebuild the image

**Comment by flow-control** [comment]
I opend up a pull request https://github.com/OXID-eSales/docker-eshop-sdk/pull/3 that should help to automate this.

Back on topic: you mentioned, that you have the vm up and running also, could you post your solution?

**Comment by patrick-blom** [comment]
Indeed, I removed the plugin with 
```
vagrant plugin uninstall vagrant-triggers
```
After the removement the vm starts as expected. Then I followed the instructions until the  composer create-project command, the command ends with the following error:

```
` - Installing ocramius/package-versions (1.4.0): Loading from cache Plugin installation failed, rolling back

Removing ocramius/package-versions (1.4.0)
[RuntimeException]
Could not delete /var/www/htdocs/oxid615-CE/vendor/ocramius/package-versions/src/PackageVersions:`
```

I fixed that bei clearing the composer cache and running the update command again as described in the eShop documentation.

```
vagrant ssh
vagrant@oxideshop:~$ cd /var/www/oxideshop
vagrant@oxideshop:/var/www/oxideshop$ composer clear-cache
vagrant@oxideshop:/var/www/oxideshop$ rm -rf vendor
vagrant@oxideshop:/var/www/oxideshop$ composer update --no-plugins --no-scripts
vagrant@oxideshop:/var/www/oxideshop$ composer update 
```

If that command completes, the vm is ready to go an you can enter the setup under http://www.oxideshop.local/Setup


**Tipp:** The machine comes by default with 512MB RAM, thats not enough for some composer commands. So I added some values to the personal.yml.

```
~/repositories/github/oxvm_eshop(b-6.1) » cat personal.yml
---
# Override any variable from 'ansible/vars/oxideshop.yml' and 'base_vm/ansible/vars/default.yml'
#
# Note: Do not rename this file as `personal.yml` and just leave it empty/unchanged. This will
# cause an error like "NoMethodError: undefined method `each_pair' for nil:NilClass" to appear.
vagrant_local:
  vm:
    memory: '2048'
php:
  version: 7.3
  composer:
    prestissimo:
      install: true
selenium:
  install: true
```

**Comment by PirxDanford** [comment]
Hi, thank you for the feedback. I have removed the vagrant-triggers from the README as indeed it is not required anymore.
